name: fake_firebase_performance
description: Fake Firebase Performance for use during Flutter unit & widget tests.
version: 1.0.0
homepage: https://philippbauer.me/
repository: https://github.com/CiriousJoker/fake_firebase_performance

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_core: any
  firebase_performance: ">=0.8.0 <1.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.1

flutter:
